---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: C:\\git\\DOB_Capstone2\\kubeconfig_myapp-eks-cluster